core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
  
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"
  
urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('create-gig/', views.ManageGigView.as_view(), name="ManageGigView"),
    path('gig/<int:pk>/', views.GigDetailView.as_view(), name="GigDetailView"),
    path('order-gig/<int:pk>/', views.GigOrderView.as_view(), name="GigOrderView"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='RegisterView'),
    path('profile/', views.ProfilePageView.as_view(), name='ProfilePageView'),
    path('profile-edit/', views.ProfileEditView.as_view(), name='ProfileEditView'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

store/models.py
from django.db import models
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
  
    @staticmethod
    def get_all_categories():
        return Category.objects.all()
  
    def __str__(self):
        return self.name


class Gig(models.Model):
    profile = models.ForeignKey("users.Profile", on_delete=models.CASCADE, related_name="gigs")
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    description = models.TextField()
    image = models.ImageField(upload_to='uploads/gig/')

    @staticmethod
    def get_gig_by_id(ids):
        return Gig.objects.filter(id__in=ids)
  
    @staticmethod
    def get_all_gig():
        return Gig.objects.all()
  
    @staticmethod
    def get_all_gig_by_categoryid(category_id):
        if category_id:
            return Gig.objects.filter(category=category_id)
        else:
            return Gig.get_all_gig()

    @property
    def get_basic_package(self):
        try:
            return self.packages.filter(package_type=1).order_by('-id').first()
        except:
            return None

    @property
    def get_standard_package(self):
        try:
            return self.packages.filter(package_type=2).order_by('-id').first()
        except:
            return None

    @property
    def get_premium_package(self):
        try:
            return self.packages.filter(package_type=3).order_by('-id').first()
        except:
            return None

    @property
    def get_all_packages(self):
        return list([self.get_basic_package,self.get_standard_package,self.get_premium_package])

    def get_absolute_url(self):
        return reverse('store:GigDetailView', kwargs={'pk': self.id})

PACKAGE_TYPES = (
    (1, 'Basic'),
    (2, 'Standard'),
    (3, 'Premium'),
)

class GigPackage(models.Model):
    gig = models.ForeignKey("store.Gig", on_delete=models.CASCADE, related_name="packages")
    price = models.IntegerField(default=0)
    package_description = models.TextField(null=True, blank=True)
    source_files = models.BooleanField(default=False)
    package_type = models.IntegerField(choices=PACKAGE_TYPES, null=True, blank=True)
    delivery = models.PositiveIntegerField(default=1)


# sk_test_ac9c389e97105d6033220fcdecddc451dd259bfc

# pk_test_260c5a2f79ad98f781f41ad29c177b5b15e07fc4

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    ROLE_CHOICES = (
        ('c', 'client'),
        ('s', 'seller'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(default='default-profile.png', upload_to='profile_pics/')
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, default="c")
    country = models.CharField(max_length=255, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    @property
    def get_all_gigs(self):
        try:
            return self.gigs.all()
        except:
            return None
  
    def register(self):
        self.save()
  
    @staticmethod
    def get_profile_by_email(email):
        try:
            return Profile.objects.get(user__email=email)
        except:
            return False
  
    def isExists(self):
        if Profile.objects.filter(user__email=self.email):
            return True
  
        return False

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_image_url(self):
        try:
            return self.image.url
        except:
            return ''


@receiver(post_save, sender=User)
def create_profile(sender, created, instance, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

store/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Gig, GigPackage

class CreateGigForm(forms.ModelForm):
    category = forms.CharField(max_length=150, required=True)

    class Meta:
        model = Gig
        fields = ['name', 'image', 'description']

class CreatePackageForm(forms.ModelForm):
    class Meta:
        model = GigPackage
        fields = ['price', 'package_description', 'delivery']

store/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import View, CreateView
from django.views.generic.detail import DetailView

from store.forms import CreateGigForm, CreatePackageForm
from store.models import Category, Gig

# Create your views here.

class HomeView(View):
    def get(self, request):
        gigs = Gig.objects.all().order_by('-id')
        context = {'gigs': gigs}
        return render(request, 'store/home.html', context)

# class ManageGigView(CreateView):
#     model = Gig
#     fields = ['name', 'price', 'image', 'description']
#     template_name = 'store/create-gig.html'

#     def form_valid(self, form):
#         category_name = self.request.POST.get('category', None)
#         category, created = Category.objects.get_or_create(name = category_name)
#         form.instance.profile = self.request.user.profile
#         form.instance.category = category
#         return super().form_valid(form)

class ManageGigView(View):
    def get(self, request):
        form = CreateGigForm()
        package_form = CreatePackageForm()
        context = {'form': form, 'package_form': package_form}
        return render(request, 'store/create-gig.html', context)

    def post(self, request):
        print(request.POST)
        form = CreateGigForm(request.POST, request.FILES)
        package_form = CreatePackageForm(request.POST)
        if form.is_valid() and package_form.is_valid():
            gig_ins = form.save(commit=False)
            category_name = self.request.POST.get('category', None)
            category = Category.objects.filter(name__iexact = category_name).first()

            if not category:
                category = Category.objects.create(name = category_name)

            gig_ins.profile = self.request.user.profile
            gig_ins.category = category
            gig_ins.save()

            prices = request.POST.getlist('price', None)
            package_descriptions = request.POST.getlist('package_description', None)
            deliverys = request.POST.getlist('delivery', None)
            package_types = request.POST.getlist('package_type', None)

            for i in range(3):
                try:
                    price = list(prices)[i]
                except:
                    price = None
                try:
                    package_description = list(package_descriptions)[i]
                except:
                    package_description = None
                try:
                    delivery = list(deliverys)[i]
                except:
                    delivery = None
                try:
                    source_file = request.POST.get(f'source_{i+1}', None)
                except:
                    source_file = None

                package_form = CreatePackageForm({
                'price': price,
                'package_description': package_description,
                'delivery': delivery,
                'source_file': source_file,
                })

                if package_form.is_valid():
                    package = package_form.save(commit = False)
                    package.gig = gig_ins
                    package.package_type = package_types[i]
                    package.save()

            return HttpResponseRedirect(gig_ins.get_absolute_url())

        context = {'form': form, 'package_form': package_form}
        return render(request, 'store/create-gig.html', context)


class GigDetailView(DetailView):
    model = Gig
    template_name = 'store/detail-gig.html'


class GigOrderView(View):
    def get(self, request, pk):
        package = request.GET.get('package', None)
        gig = get_object_or_404(Gig, pk = pk)
        package = gig.packages.filter(package_type = package).first()
        price = 0
        if package:
            price = package.price
        context = {'gig': gig, 'price': price}
        return render(request, 'store/order-page.html', context)

templates/store/create-gig.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<section class="container">
  <div class="content-section card p-4">
    <div class="media row d-flex align-items-center mb-4">
      <div class="col-md-4">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">

      </div>
      <div class="col-md-8">
        <div class="media-body ms-4">
          <h3 class="account-heading lead">{{ user.username }}</h3>
          <p class="text-secondary">{{ user.email }}</p>
          {% if user.profile.role == "s" %}
            <small class="text-danger">{{user.profile.get_role_display}} Account</small>
            {% else %}
            <small class="text-success">{{user.profile.get_role_display}} Account</small>
          {% endif %}
        </div>

      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <h2 class="mb-4">Create Gig</h2>
            {{ form|crispy }}

            <div class="row">
              <div class="col-md-4 mt-4">
                <h3 class="display-4 text-center">Basic</h3>
                <input type="hidden" name="package_type" value="1">
                {{ package_form|crispy }}
                <input type="checkbox" name="source_1">
              </div>
              <div class="col-md-4 mt-4">
                <h3 class="display-4 text-center">Standard</h3>
                <input type="hidden" name="package_type" value="2">
                {{ package_form|crispy }}
                <input type="checkbox" name="source_2">
              </div>
              <div class="col-md-4 mt-4">
                <h3 class="display-4 text-center">Premium</h3>
                <input type="hidden" name="package_type" value="3">
                {{ package_form|crispy }}
                <input type="checkbox" name="source_3">
              </div>
            </div>
              {% comment %} <div id="div_id_category" class="form-group mt-2">
              <label for="id_category" class=" requiredField">Category<span class="asteriskField">*</span> </label>
              <div class="">
                <input type="text" name="category" maxlength="255" class="textinput textInput form-control" required="" id="id_category">
              </div>
            </div> {% endcomment %}
        </fieldset>
        <div class="form-group mt-4">
            <button class="btn btn-outline-info" type="submit">Create</button>
        </div>
    </form>
  </div>
</section>

{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}

templates/store/detail-gig.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
<style>
    #product_detail_left{
        margin-right: 20px;
        flex: 0.7;
    }
    .product_detail_heading{
        font-size: x-large;
        font-weight: bold;
        margin-bottom: 20px;
    }
    .product_detail_p{
        font-weight: lighter;
    }
    
    #product_detail_right{
        flex: 0.3;
    }
    .product_detail_block{
        padding: 15px;
        border:1px solid var(--outline);
        border-radius: 5px;
        margin-bottom: 10px;
    }
    .product_detail_block > #product_detail_block_price{
        font-size: xx-large;
        color: var(--primary_blue);
        margin-bottom: 5px;
    }
    .product_detail_block > #product_detail_block_name{
        font-size: medium;
        color: var(--gray);
        font-weight: lighter;
        margin-bottom: 15px;
    }
    .product_detail_block > #product_detail_block_location,
    .product_detail_block > #product_detail_block_date{
        display: inline;
        font-size: smaller;
        color: var(--text-fadded);
    }
    .product_detail_block > #product_detail_block_date{
        float: right;
    }
    .product_detail_block > #product_detail_seller_heading{
        font-size: larger;
    }
    
    #product_detail_seller_avatar_cont{
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 20px;
    }
    #product_detail_seller_avatar{
        width: 50px;
        height: 50px;
        font-size: 25px;
        border-radius: 50%;
        background-size: cover;
        background-position: center;
    }
    #product_detail_seller_user{
        color: var(--primary_blue);
        flex: 1;
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-left: 10px;
    }
    #product_detail_seller_user > i{
        font-size: x-large;
    }
    .addToCart_btn{
        text-decoration: none;
        color: white;
        background-color: var(--primary_blue);
        padding: 10px;
        border-radius: 5px;
    }
</style>

<style>
    .slide_container {
        position: relative;
        padding: 15px;
        border:1px solid var(--outline);
        border-radius: 5px;
        margin-bottom: 10px;
    }

    /* Hide the images by default */
    .mySlides {
        display: none;
        min-height: 70vh;
        background-color: black;
    }
    .mySlides > img{
        object-fit: contain;
        height: 70vh;
    }
    
    /* Add a pointer when hovering over the thumbnail images */
    .cursor {
        cursor: pointer;
    }
    
    /* Next & previous buttons */
    .prev,
    .next {
        cursor: pointer;
        position: absolute;
        top: 40%;
        width: auto;
        padding: 16px;
        margin-top: -50px;
        color: white;
        font-weight: bold;
        font-size: 20px;
        border-radius: 0 3px 3px 0;
        user-select: none;
        -webkit-user-select: none;
    }
    
    /* Position the "next button" to the right */
    .next {
        right: 15px;
        border-radius: 3px 0 0 3px;
    }
    
    /* On hover, add a black background color with a little bit see-through */
    .prev:hover,
    .next:hover {
        background-color: rgba(0, 0, 0, 0.8);
    }
    
    .slide_row {
        display: flex;
        overflow-x: scroll;
        max-height: 20vh;
    }
    .slide_row::-webkit-scrollbar {
        width: 10px;
    }
    /* .row:after {
        content: "";
        display: table;
        clear: both;
    } */
    
    /* Six columns side by side */
    .slide_scolumn {
        flex: 0.1;
    }
    .slide_scolumn > img{
        object-fit: contain;
        width: 100%;
        height: 100%;
    }
    
    /* Add a transparency effect for thumnbail images */
    .demo {
        opacity: 0.6;
    }
    .demo:hover {
        opacity: 1;
    }
    
    .active{
        padding: 5px;
        opacity: 1;
        border: 2px solid var(--primary_blue);
    }

    #numbertext{
        color: #f2f2f2;
        font-size: 12px;
        padding: 10px 12px;
        position: absolute; top: 20px; left: 20px;
    }
</style>
{% endblock ExtraCss %}


{% block content %}

{% block header %}
{% endblock header %}

{% comment %} <section class="container">
  <div class="content-section card p-4">

    {{object}}
  </div>
</section> {% endcomment %}
<section class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="slide_container container">
                <div id="numbertext">0 / 0</div>
                <div class="mySlides">
                    <img src={{object.image.url}} style="width:100%">
                </div>
                {% comment %} {%for image_model in object.album.images.all%}
                    <div class="mySlides">
                        <img src={{image_model.image.url}} style="width:100%">
                    </div>
                {%endfor%} {% endcomment %}
                <!-- Next and previous buttons -->
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>
                <!-- Thumbnail images -->
                <div class="slide_row no_scroll">
                    <div class="slide_scolumn">
                        <img class="demo cursor" src={{object.image.url}} style="width:100%" onclick="currentSlide(this)" alt="IMG">
                    </div>
                    {% comment %} {%for image_model in object.album.images.all%}
                    <div class="slide_scolumn">
                        <img class="demo cursor" src={{object.image.url}} style="width:100%" onclick="currentSlide(this)" alt="IMG">
                    </div>
                    {%endfor%} {% endcomment %}
                </div>
            </div>
    
            <div class="card p-4">
                <p class="product_detail_heading">Description:</p>
                <p class="product_detail_p">
                    {{object.description}}
                </p>
            </div>
        </div>

        <div class="col-md-3 p-4">
            <div class="accordion" id="gig_pacakges_accordion">
                {% for package in object.get_all_packages %}
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="package-{{package.get_package_type_display}}-accordion">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{package.get_package_type_display}}" aria-expanded="false" aria-controls="collapse-{{package.get_package_type_display}}">
                            <p class="m-0 lead">
                                <span class="text-success">$ {{package.price}}</span> <strong>{{package.get_package_type_display}}</strong>
                            </p>
                        </button>
                      </h2>
                      <div id="collapse-{{package.get_package_type_display}}" class="accordion-collapse collapse" aria-labelledby="package-{{package.get_package_type_display}}-accordion" data-bs-parent="#gig_pacakges_accordion">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col-12 py-2">
                                    <p class="text-muted m-0"><i><i class="far fa-clock"></i> {{package.delivery}} Days Delivery</i></p>
                                </div>
                                <div class="col-12 py-2">
                                    <p class="text-muted m-0">
                                        {% if package.source_files %}
                                            <i class="fas fa-check text-success"></i>
                                        {% else %}
                                            <i class="fas fa-times text-danger"></i>
                                        {% endif %}
                                        Source Files
                                    </p>
                                </div>
                                <div class="col-12">
                                    <a href="{% url 'store:GigOrderView' pk=object.id %}?package={{package.package_type}}" class="btn btn-success w-100 mt-3">Order Now ({{package.price}}$)</a>
                                </div>
                            </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

</section>
{% endblock content %}


{% block ExtraJs %}
<script>
    var slideIndex = 1;
    showSlides(slideIndex);
    
    // Next/previous controls
    function plusSlides(n) {
        showSlides(slideIndex += n);
    }
    
    // Thumbnail image controls
    function currentSlide(element) {
        parent = element.parentNode
        grandparent = parent.parentNode
        for (let i = 0; i < grandparent.children.length; i++) {
            if (grandparent.children[i].children[0].alt === element.alt) {
                // console.log('matched!',i)
                return showSlides(slideIndex = i + 1)
            }
        }
    }
    
    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("demo");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].classList.remove("active");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].classList.add("active");
        var numbertext = document.getElementById("numbertext");
        numbertext.innerText = `${slideIndex} / ${slides.length}`
    }
    
    
</script>
{% endblock ExtraJs %}

templates/store/home.html
{% extends 'base.html' %}
{% load static %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% comment %} <h1>HomePage</h1>
{% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'users:ProfileView' %}">Profile</a>
    <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
{% else %}
    <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
    <a class="nav-item nav-link" href="{% url 'users:RegisterView' %}">Register</a>
{% endif %} {% endcomment %}

<main class="m-4">
    <section class="mt-4 text-center">
        <h3>Popular Categories</h3>
        <div class="row carousel-cont">
            <div class="col">
                <div class="category-cont">
                    <div class="overlay"></div>
                    <img src="https://cdn.kwork.com/files/menu_cover/x1/1084-1620898316.jpg" alt=" ">
                    <!-- <p class="sub-heading ">Category</p> -->
                </div>
            </div>
            <div class="col ">
                <div class="category-cont ">
                    <div class="overlay "></div>
                    <img src="https://cdn.kwork.com/files/menu_cover/x1/1084-1620898316.jpg " alt="">
                    <!-- <p class="sub-heading">Category</p> -->
                </div>
            </div>
            <div class="col">
                <div class="category-cont">
                    <div class="overlay"></div>
                    <img src="https://cdn.kwork.com/files/menu_cover/x1/1084-1620898316.jpg" alt=" ">
                    <!-- <p class="sub-heading ">Category</p> -->
                </div>
            </div>
            <div class="col ">
                <div class="category-cont ">
                    <div class="overlay "></div>
                    <img src="https://cdn.kwork.com/files/menu_cover/x1/1084-1620898316.jpg " alt="">
                    <!-- <p class="sub-heading">Category</p> -->
                </div>
            </div>
        </div>
    </section>

    <section class="mt-4 text-center">
        <h3 class="mb-4">Explore More</h3>
        <div class="row">
            {% for gig in gigs %}
            <div class="col-sm-6 col-md-4">
                <div class="shop__thumb">
                    <a href="{{gig.get_absolute_url}}">
                        <div class="shop-thumb__img">
                            <img src="{{gig.image.url}}" class="img-responsive" alt="..." height="300px">
                        </div>
                        <h5 class="shop-thumb__title">
                            {{gig.name}}
                        </h5>
                        <div class="shop-thumb__price">
                            $ {{gig.get_basic_package.price}}
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}

templates/store/order-page.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<section class="container">
  <div class="content-section card p-4">
    <h1 class="text-center">Place Your Order</h1>
    <form id="paymentForm">
        <div class="form-group">
          <label for="first-name">First Name</label>
          <input class="form-control" type="text" id="first-name"/>
        </div>
        <div class="form-group">
          <label for="last-name">Last Name</label>
          <input class="form-control" type="text" id="last-name"/>
        </div>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input class="form-control" type="email" id="email-address" required/>
        </div>
        <div class="form-group">
          <label for="amount">Amount</label>
          <input class="form-control" type="tel" id="amount" value="{{price}}" disabled/>
        </div>
        <div class="form-submit">
          <button class="btn btn-primary mt-4" type="button" onclick="payWithPaystack()">Pay</button>
        </div>
    </form>
</div>
</section>

{% endblock content %}


{% block ExtraJs %}
    <script src="https://js.paystack.co/v1/inline.js"></script> 

    <script>
        var paymentForm = document.getElementById('paymentForm');
        paymentForm.addEventListener('submit', payWithPaystack, false);
        function payWithPaystack() {
          var handler = PaystackPop.setup({
            key: 'pk_test_260c5a2f79ad98f781f41ad29c177b5b15e07fc4', // Replace with your public key
            email: document.getElementById('email-address').value,
            amount: document.getElementById('amount').value * 100, // the amount value is multiplied by 100 to convert to the lowest currency unit
            currency: 'ZAR', // Use GHS for Ghana Cedis or USD for US Dollars
            ref: 'YOUR_REFERENCE', // Replace with a reference you generated
            callback: function(response) {
              //this happens after the payment is completed successfully
              var reference = response.reference;
              alert('Payment complete! Reference: ' + reference);
              // Make an AJAX call to your server with the reference to verify the transaction
            },
            onClose: function() {
              alert('Transaction was not completed, window closed.');
            },
          });
          handler.openIframe();
        }
    </script>
{% endblock ExtraJs %}