core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
  
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"
  
urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('create-gig/', views.ManageGigView.as_view(), name="ManageGigView"),
    path('gig/<int:pk>/', views.GigDetailView.as_view(), name="GigDetailView"),
    path('order-gig/<int:pk>/', views.GigOrderView.as_view(), name="GigOrderView"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='RegisterView'),
    path('profile/', views.ProfilePageView.as_view(), name='ProfilePageView'),
    path('profile-edit/', views.ProfileEditView.as_view(), name='ProfileEditView'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    ROLE_CHOICES = (
        ('c', 'client'),
        ('s', 'seller'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(default='default-profile.png', upload_to='profile_pics/')
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, default="c")
    country = models.CharField(max_length=255, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    @property
    def get_all_gigs(self):
        try:
            return self.gigs.all()
        except:
            return None
  
    def register(self):
        self.save()
  
    @staticmethod
    def get_profile_by_email(email):
        try:
            return Profile.objects.get(user__email=email)
        except:
            return False
  
    def isExists(self):
        if Profile.objects.filter(user__email=self.email):
            return True
  
        return False

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_image_url(self):
        try:
            return self.image.url
        except:
            return ''


@receiver(post_save, sender=User)
def create_profile(sender, created, instance, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'role']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def  post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, f'Your account has been created!')
            login(request, user)
            return redirect('store:HomeView')
        return render(request, 'users/register.html', {'form': form})


class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {
            'u_form': u_form,
            'p_form': p_form
        }

        return render(request, 'users/profile-edit.html', context)

    def post(self, request):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:ProfileEditView')
        context = {
            'u_form': u_form,
            'p_form': p_form
        }
        return render(request, 'users/profile-edit.html', context)


class ProfilePageView(LoginRequiredMixin, View):
    def get(self, request):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {
            'u_form': u_form,
            'p_form': p_form
        }

        return render(request, 'users/profile.html', context)

    def post(self, request):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:ProfileEditView')
        context = {
            'u_form': u_form,
            'p_form': p_form
        }
        return render(request, 'users/profile.html', context)

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<section class="container">
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="mb-4">Log In!</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group pt-3">
        <button class="btn btn-outline-info " type="submit">Log In</button>
      </div>
      <div class="pt-3">
        <small class="text-muted">
          Need an account ? <a class="ml-2" href="{% url 'users:RegisterView' %}">Sign Up Now</a>
        </small>
      </div>
    </form>
  </div>
</section>

{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}

templates/users/logout.html
{% extends 'base.html' %}
{% load static %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<section class="text-center">
  <h2 class="display-4">You have been logged out</h2>
  <div class="pt-3">
    <a href="{% url 'users:login' %}" class="text-muted">Log In Again</a>
  </div>
</section>

{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}

templates/users/profile-edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<section class="container">
  <div class="content-section card p-4">
    <div class="media d-flex align-items-center mb-4">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body ms-4">
        <h3 class="account-heading lead">{{ user.username }}</h3>
        <p class="text-secondary">{{ user.email }}</p>
        {% if user.profile.role == "s" %}
          <small class="text-danger">{{user.profile.get_role_display}} Account</small>
          {% else %}
          <small class="text-success">{{user.profile.get_role_display}} Account</small>
        {% endif %}
      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <h2 class="mb-4">Profile Info</h2>
            {{ u_form|crispy }}
            <br>
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group mt-4">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
  </div>
</section>

{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
    <style>
        .icon-box.medium {
            font-size: 20px;
            width: 50px;
            height: 50px;
            line-height: 50px;
        }
        .icon-box {
            font-size: 30px;
            margin-bottom: 33px;
            display: inline-block;
            color: #ffffff;
            height: 65px;
            width: 65px;
            line-height: 65px;
            
            text-align: center;
            border-radius: 0.3rem;
        }
        .social-icon-style2 li a {
            display: inline-block;
            font-size: 14px;
            text-align: center;
            color: #ffffff;
            
            height: 41px;
            line-height: 41px;
            width: 41px;
        }
        .rounded-3 {
            border-radius: 0.3rem !important;
        }
        
        .social-icon-style2 {
            margin-bottom: 0;
            display: inline-block;
            padding-left: 10px;
            list-style: none;
        }
        
        .social-icon-style2 li {
            vertical-align: middle;
            display: inline-block;
            margin-right: 5px;
        }
        
        a, a:active, a:focus {
            color: #616161;
            text-decoration: none;
            transition-timing-function: ease-in-out;
            -ms-transition-timing-function: ease-in-out;
            -moz-transition-timing-function: ease-in-out;
            -webkit-transition-timing-function: ease-in-out;
            -o-transition-timing-function: ease-in-out;
            transition-duration: .2s;
            -ms-transition-duration: .2s;
            -moz-transition-duration: .2s;
            -webkit-transition-duration: .2s;
            -o-transition-duration: .2s;
        }
        
        .text-secondary, .text-secondary-hover:hover {
            
        }
        .display-25 {
            font-size: 1.4rem;
        }
        
        .text-primary, .text-primary-hover:hover {
            color: #ff712a !important;
        }
        
        p {
            margin: 0 0 20px;
        }
        
        .mb-1-6, .my-1-6 {
            margin-bottom: 1.6rem;
        }
    </style>
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-md-7 col-lg-4 mb-5 mb-lg-0 wow fadeIn">
            <div class="card border-0 shadow">
                <img src="{{user.profile.get_image_url}}" alt="{{user.username}}-image">
                <div class="card-body p-1-9 p-xl-5">
                    <div class="mb-4">
                        <h3 class="h4 mb-0">{{user.username}}</h3>
                        <span class="text-primary">{{user.profile.get_role_display}}</span>
                    </div>
                    <ul class="list-unstyled mb-4">
                        <li class="mb-3"><i class="far fa-envelope display-25 me-3 text-secondary"></i>{{user.email}}</li>
                        <li><i class="fas fa-map-marker-alt display-25 me-3 text-secondary"></i>{{user.profile.country}}</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="ps-lg-1-6 ps-xl-5">
                <div class="mb-4">
                    <div class="border py-2 px-4 mb-4">
                        <h3 class="m-0">Orders <span class="text-muted">- 0</span></h3>
                    </div>

                    <div class="border py-2 px-4 m-0 mb-4 row" style="overflow-x:auto;">
                        <table>
                             <tbody>
                               <tr>
                                 <td style="min-width: 60px;">
                                    <img src="https://fiverr-res.cloudinary.com/t_medium5,q_auto,f_auto/gigs/214000555/original/5138a5f4356418db2306bd6e6711e4750c4182dd.png" height="50px">
                                 </td>
                                 <td style="min-width: 60px;">
                                    <div class="d-flex align-items-center">
                                        <div class="rounded-img-cont" style="background-image: url('{{user.profile.get_image_url}}');"></div>
                                        <span class="m-0 text-muted ms-2"><strong>{{user.username}}</strong></span>
                                    </div>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <p class="m-0 text-muted"><strong>Price</strong></p>
                                    <small>50$</small>
                                 </td>
                                 <td class="text-center" style="min-width: 100px;">
                                    <p class="m-0 text-muted"><strong>Due In</strong></p>
                                    <small>21, Dec, 2021</small>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <p class="m-0 text-muted"><strong>Status</strong></p>
                                    <small class="badge bg-primary">In Progress</small>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <a href="#" class="text-success">View</a>
                                 </td>
                               </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="border py-2 px-4 m-0 mb-4 row" style="overflow-x:auto;">
                        <table>
                             <tbody>
                               <tr>
                                 <td style="min-width: 60px;">
                                    <img src="https://fiverr-res.cloudinary.com/t_medium5,q_auto,f_auto/gigs/214000555/original/5138a5f4356418db2306bd6e6711e4750c4182dd.png" height="50px">
                                 </td>
                                 <td style="min-width: 60px;">
                                    <div class="d-flex align-items-center">
                                        <div class="rounded-img-cont" style="background-image: url('{{user.profile.get_image_url}}');"></div>
                                        <span class="m-0 text-muted ms-2"><strong>{{user.username}}</strong></span>
                                    </div>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <p class="m-0 text-muted"><strong>Price</strong></p>
                                    <small>50$</small>
                                 </td>
                                 <td class="text-center" style="min-width: 100px;">
                                    <p class="m-0 text-muted"><strong>Due In</strong></p>
                                    <small>21, Dec, 2021</small>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <p class="m-0 text-muted"><strong>Status</strong></p>
                                    <small class="badge bg-primary">In Progress</small>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <a href="#" class="text-success">View</a>
                                 </td>
                               </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="border py-2 px-4 m-0 mb-4 row" style="overflow-x:auto;">
                        <table>
                             <tbody>
                               <tr>
                                 <td style="min-width: 60px;">
                                    <img src="https://fiverr-res.cloudinary.com/t_medium5,q_auto,f_auto/gigs/214000555/original/5138a5f4356418db2306bd6e6711e4750c4182dd.png" height="50px">
                                 </td>
                                 <td style="min-width: 60px;">
                                    <div class="d-flex align-items-center">
                                        <div class="rounded-img-cont" style="background-image: url('{{user.profile.get_image_url}}');"></div>
                                        <span class="m-0 text-muted ms-2"><strong>{{user.username}}</strong></span>
                                    </div>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <p class="m-0 text-muted"><strong>Price</strong></p>
                                    <small>50$</small>
                                 </td>
                                 <td class="text-center" style="min-width: 100px;">
                                    <p class="m-0 text-muted"><strong>Due In</strong></p>
                                    <small>21, Dec, 2021</small>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <p class="m-0 text-muted"><strong>Status</strong></p>
                                    <small class="badge bg-primary">In Progress</small>
                                 </td>
                                 <td class="text-center" style="min-width: 60px;">
                                    <a href="#" class="text-success">View</a>
                                 </td>
                               </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
                {% if user.is_authenticated %}
                    <div class="mb-4">
                        <div class="border py-2 px-4 mb-4">
                            <div class="d-flex align-items-center justify-content-between">
                                <h3 class="m-0">Gigs <span class="text-muted">- 0</span></h3>
                                <a href="{% url 'store:ManageGigView' %}" class="btn btn-outline-success btn-sm">Create New Gig</a>
                            </div>
                        </div>

                        <div class="row justify-content-center text-center">
                            {% for gig in user.profile.get_all_gigs %}
                                <div class="col-md-6 col-lg-4 mb-4">
                                    <a href="{{gig.get_absolute_url}}">
                                        <div class="card">
                                            <img src="{{gig.image.url}}" class="card-img-top" alt="...">
                                            <div class="card-body">
                                                <p class="text-muted">{{gig.name}}</p>
                                                <p class="text-end m-0"><a href="#" class="text-success">Starting At {{gig.get_basic_package.price}}$</a></p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}

                            <div class="col-md-6 col-lg-4 mb-4">
                                <div class="card">
                                    <img src="https://fiverr-res.cloudinary.com/images/t_medium7,q_auto,f_auto,q_auto,f_auto/gigs/214000555/original/5138a5f4356418db2306bd6e6711e4750c4182dd/be-your-professional-django-python-developer.png" class="card-img-top" alt="...">
                                    <div class="card-body">
                                    <p class="text-muted">I will be your front end developer.</p>
                                    <p class="text-end m-0"><a href="#" class="text-success">Starting At 10$</a></p>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-4 mb-4">
                                <div class="card">
                                    <img src="https://fiverr-res.cloudinary.com/images/t_medium7,q_auto,f_auto,q_auto,f_auto/gigs/214000555/original/5138a5f4356418db2306bd6e6711e4750c4182dd/be-your-professional-django-python-developer.png" class="card-img-top" alt="...">
                                    <div class="card-body">
                                    <p class="text-muted">I will be your front end developer.</p>
                                    <p class="text-end m-0"><a href="#" class="text-success">Starting At 10$</a></p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}


{% block content %}
{% block header %}
{% endblock header %}

<section class="container">
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="mb-4">Join today!</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info " type="submit">Sign Up</button>
      </div>
      <div class="pt-3">
        <small class="text-muted">
          Already have an account ? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
        </small>
      </div>
    </form>
  </div>
</section>

{% endblock content %}


{% block ExtraJs %}
{% endblock ExtraJs %}